# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a83158c4e6a5ec9c9494418bb79d834b543614c15d59aca86f94698197bff6d5db10e9bd97a990b0ef106f1d1743cb715c12123a6956caf7f45e712898984b2

test:
  secret_key_base: c847e00a5ea9f8aa057494d9c371998e57f57a0a31b9fb2cbe4ccc1db2ce3328717ba33a3c5b0ad95758518986cbba8d0c58678962954f8b65c75865ea2340df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
